### ISSUE TITLE
Reihenfolge der PatternInstance-Variablen ändert sich bei jedem GET-Request

### ISSUE THREAD

**Issue by nymvno** [ckrieger/ADDComplianceChecking#6]
Das führt dazu, dass in der Monitoring-View die Variablen immer wieder Plätze tauschen und steht einer übersichtlichen View eher im Weg..

**Comment by ckrieger** [comment]
du könntest in angular eine pipe implementieren, welche die varibalen alphabetisch nach ihrem key sortiert.

https://angular.io/guide/pipes
